version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    ports:
      - "18000:8000"
    volumes:
      - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  dynamodb-admin:
    image: instructure/dynamo-local-admin
    depends_on:
      - dynamodb-local
    ports:
      - "18001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://dynamodb-local:8000

  lambda-local:
    build: .
    volumes:
      - ./aws-credentials:/root/.aws
    depends_on:
      - dynamodb-local
    ports:
      - "18080:8080"
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
      - LINE_ACCESS_TOKEN=$LINE_ACCESS_TOKEN
